name: Sync Upstream Changes

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 完整历史

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v1.2.0  # 或其他如 dabreadman/sync-upstream-repo@v1.0.0
        with:
          target_branch: main  # 你的分支
          upstream_repo: https://github.com/ginibond/ginibond.git  # 原仓库 URL
          upstream_branch: main  # 上游分支
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}  # 使用内置 token，无需额外设置

      - name: Commit if changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config user.name "GitHub Action"
            git config user.email "action@github.com"
            git add .
            git commit -m "Sync upstream changes"
            git push
          fi
